name: 13_te_estimate_v1

input:
  use_neutral: true
score:
  mode: te_leave_one_out
output:
  save_score: true
  save_coef: true
  save_resid_var_full: true
  save_resid_var_reduced: false
  save_te_json: true
